### ISSUE TITLE
Memory problem in polymorphic skeleton ?

### ISSUE THREAD

**Issue by gendx** [fbb-git/bisoncpp#6]
Hello,

In the skeleton for polymorphic SType : [bisonc++/skeletons/bisonc++polymorphic](https://github.com/fbb-git/bisoncpp/blob/master/bisonc%2B%2B/skeletons/bisonc%2B%2Bpolymorphic)
Correct me if I am wrong, but the `Base` class has no virtual destructor, so the `delete d_base;` statements at lines 187 and 224 do not call the appropriate `Semantic<T>` destructors. If I am correct, it seems that virtual function are unavoidable. In that case, why re-implementing virtual tables manually with function pointers? It seems to me that having a single pointer to the vtable in each object (the virtual functions implementation) is more lightweight than having the whole "vtable" in each object (the current implementation).

Also, it would be nice to use smart pointers instead of the raw `new` and `delete` statements, to be clearer about the intended semantics and to avoid possible memory leaks ; it seems to me that a `unique_ptr<Base>` would be appropriate here.

**Comment by ElectronicRU** [comment]
I feel like smart pointers are an overkill since Base objects have a well-defined limited lifetime.

**Comment by gendx** [comment]
Well, `unique_ptr` has zero overhead at runtime, it is only about templates. And it ensures that the semantics are preserved when you modify your code. I think that using raw pointers after C++11 should really be avoided, except in specific cases.

It is true however that `shared_ptr` has a runtime overhead. For example, I benchmarked a code generated by the 4.xx version of bisonc++ (which used `shared_ptr`), and it was twice as slow as a modified code using `unique_ptr` (in the specific case of my grammar). So if your grammar follows move-only semantics, it makes sense to use a `unique_ptr` (even though it may not apply to all grammars).

But the main problem is still the lack of a virtual destructor...

**Comment by fbb-git** [comment]
Dear gendx, you wrote:

> ...
> It is true however that `shared_ptr` has a runtime overhead. For example, I
> benchmarked a code generated by the 4.xx version of bisonc++ (which used
> `shared_ptr`), and it was twice as slow as a modified code using
> `unique_ptr` (in the specific case of my grammar). 

...

Thanks for your posting about bisonc++. I think most of your valuable
suggestions have been adopted in bisonc++ V 5.00.00, which is already
available at github. V 5.00.00+ no longer uses shared_ptrs and offers several
additional new features.

Cheers,

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by gendx** [comment]
Hello,

My main concern is that the `Base` class has no virtual destructor, which means that the `delete` statements [here](https://github.com/fbb-git/bisoncpp/blob/master/bisonc%2B%2B/skeletons/bisonc%2B%2Bpolymorphic#L187) and [there](https://github.com/fbb-git/bisoncpp/blob/master/bisonc%2B%2B/skeletons/bisonc%2B%2Bpolymorphic#L224) have **unspecified behavior** (see e.g. [this](http://stackoverflow.com/questions/8599225/virtual-destructor-and-undefined-behavior#8599332)).

**Comment by fbb-git** [comment]
Dear gendx, you wrote:

> Hello,
> 
> My main concern is that the `Base` class has no virtual destructor, which means that the `delete` statements [here](https://github.com/fbb-git/bisoncpp/blob/master/bisonc%2B%2B/skeletons/bisonc%2B%2Bpolymorphic#L187) and [there](https://github.com/fbb-git/bisoncpp/blob/master/bisonc%2B%2B/skeletons/bisonc%2B%2Bpolymorphic#L224) have **unspecified behavior** (see e.g. [this](http://stackoverflow.com/questions/8599225/virtual-destructor-and-undefined-behavior#8599332)).

I understand your concern, but virtual destructors only apply to polymorphic
types, having Vtables. Bisonc++'s polymorphic semantic value types aren't
polymorphic in that sense: they are called polymorphic to reflect that
Bisonc++'s semantic value can be associated with multiple types, but different
from unions, only one type can apply to a rule whose nonterminal is associated
with that type.

I've tried to explain that in the manual; maybe that explanation should be
further clarified. If so, it won't happen very soon: I'm currently abroad,
which reduces my options for working on bisonc++ somewhat. Sorry about that.

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by gendx** [comment]
Hello,

Let me put it differently. Your code skeleton looks like this:

``` c++
class Base { /* no virtual destructor */ }

template <Tag__ tg__>
class Semantic : public Base {
    typename TypeOf<tg_>::type d_data;
    ...
}

class SType
{
    Base* d_base;
    ...
}

...
d_base = new Semantic<tag>(args...);
...
delete d_base;
```

I agree that your `Base` and `Semantic<tag>` classes don't have VTables, but you use them as polymorphic types because you define a variable of type `Base*`, assign to it a `Semantic<tag>*` and then delete it as a `Base*`.
Without a virtual destructor, only `~Base()` is called, but `~Semantic<tag>()` is never called, which is an undefined behavior and effectively leads (at best) to memory leaks because the user data is stored in the `Semantic<tag>` class (in the `d_data` field).

**Comment by fbb-git** [comment]
Dear gendx, you wrote:

> Let me put it differently. Your code skeleton looks like this:
> ...
> I agree that your `Base` and `Semantic<tag>` classes don't have VTables, but
> you use them as polymorphic types because you define a variable of type
> `Base*`, assign to it a `Semantic<tag>*` and then delete it as a `Base*`.

Well, you're right, and also: (my) yesterday evening I looked at the Base and
SType implementation, and (like you) noticed that 'delete d_base' is
incorrect. Like the way data access and cloning is handled in Base, it should
handle destruction: allowing the Semantic implementation to configure its Base
class so that Semantic objects, rather than just Base class objects are
deleted via SType's destructor. This (my) morning I added a preliminary
implementation to Bisonc++'s generated code, and a small demo grammar showed
that all constructed polymorphic semantic values were properly destroyed. So I
think we're in sync again :-)

As I wrote yesterday, I probably won't be able to complete a new release in
just one or two days, but I'll do my best to complete the new release soon.

In the meantime: thanks for your valuable remarks and suggestions.

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by gendx** [comment]
The latest version looks fine to me ! Thanks again for all your work on Bisonc++ !

**Comment by fbb-git** [comment]
Dear gendx, you wrote:

> The latest version looks fine to me ! Thanks again for all your work on
> Bisonc++ !

You're fast! Thanks for the positive feedback!

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```
