### ISSUE TITLE
Failed copy-list-initialization semantic value;

### ISSUE THREAD

**Issue by yusefmhg** [fbb-git/bisoncpp#7]
Hello,

using the bisonc++ version 4.13.01 with polymorphic semantic values, the semantic action for the production:
`vertex:    TK_KW_V coord coord coord         { $$ = { $2, $3, $4, 1.0 }; }`
was working fine (provided the `vertex` semantic type was an aggregate, in this case a class type with no protected or private members, no user-provided constructors, etc., and the semantic value of `coord` match the data members types of the class).
After upgrading to version 5.00.01 (from Debian testing repository) I got a compilation error:
`parser.y: In member function ‘void Parser::executeAction(int)’:
parser.y:85:19: error: no match for ‘operator=’ (operand types are ‘ParserBase::STYPE__ {aka Meta__::SType}’ and ‘<brace-enclosed initializer list>’)
     TK_KW_V coord coord coord         { $$ = { $2, $3, $4, 1.0 }; }
                   ^
parse.cc:636:8: note: candidate: Meta__::SType& Meta__::SType::operator=(const Meta__::SType&)
 SType &SType::operator=(SType const &other)
        ^`
Substituting the action for:
`vertex:    TK_KW_V coord coord coord         { $$ =vec4 { $2, $3, $4, 1.0 }; }`
seems to fix the problem (but the resultant parser is painfully slower than the generated by the 4.13 version). NOTE: vec4 is the class type associated with the non-terminal vertex;
Is this an expected behavior for the newer version?

EDITED:

Found the problem (in fact, is not a problem, but an expected behavior for the newer version) with the copy-list-initialization, as can be read in the `README.polymorphic-technical`:

> In the latter case (copy constructing from an existing object) Type must be a defined polymorphic semantic type (which a initializer-list isn't), as this allows the compiler to deduct the correct Tag__.

There are, still, the difference in performance between the parser generated by version 4.13.01 and the one generated by version 5.00.01 (the later is 30 times slower). The parser generated with version 5.01.00 seems faster than the generated by 5.00.01, but still much slower than the version 4.13.01, but it isn't related to this issue, so I'd consider this topic solved.

P.S. I'm sorry for the mistake (I should have read the changelog more carefully) and thanks for the great software.

**Comment by fbb-git** [comment]
Dear yusefmhg, you wrote:

> Hello,

Hi, and thanks for your posting about Bisonc++:

> using the bisonc++ version 4.13.01 with polymorphic semantic values, the semantic action for the production:
> `vertex:    TK_KW_V coord coord coord         { $$ = { $2, $3, $4, 1.0 }; }`
> was working fine (provided the `vertex` semantic type was an aggregate, in
> this case a class type with no protected or private members, no user-provided
> constructors, etc., and the semantic value of `coord` match the data members
> types of the class).

OK

> After upgrading to version 5.00.01 (from Debian testing repository) I got a compilation error:
> `parser.y: In member function ‘void Parser::executeAction(int)’:
> parser.y:85:19: error: no match for ‘operator=’ (operand types are
> ‘ParserBase::STYPE__ {aka Meta__::SType}’ and ‘<brace-enclosed initializer
> list>’)
> 
> ```
>  TK_KW_V coord coord coord         { $$ = { $2, $3, $4, 1.0 }; }
>                ^
> ```
> 
> parse.cc:636:8: note: candidate: Meta__::SType& Meta__::SType::operator=(const Meta__::SType&)
>  SType &SType::operator=(SType const &other)

That's correct. There's no way for the compiler to deuct what semantic value
you have in mind. If you explicitly specify the requested semantic type
(vertex?) the compiler _can_ deduct what you mean and compilation should
succeed. E.g.,

```
  TK_KW_V coord coord coord         { $$ = vertex{ $2, $3, $4, 1.0}; }
```

> Substituting the action for:
> `vertex:    TK_KW_V coord coord coord         { $$ =vec4 { $2, $3, $4, 1.0 }; }`

This is probabaly the same as my vertex suggestion: maybe your semantic value is
'vect4' rather than 'vertex'?

> seems to fix the problem (but the resultant parser is painfully slower than the generated by the 4.13 version).
> Is this an expected behavior for the newer version?

No, there are no changes in the parser's parsing algorithm.  polymorphic
semantic values do not use shared_ptrs anymore, and that improves rather than
slows down the parser's speed. Also, none of the tests performed so far
indicate any (painful or not) speed reduction, which makes it hard for me to
give you a conclusive answer. You might consider profiling your program to
find the location of the bottleneck. I hope this helps you to solve your
problem.

Cheers,

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by fbb-git** [comment]
Dear yusefmhg, you wrote:

> Hello,
> 
> using the bisonc++ version 4.13.01 with polymorphic semantic values, the
> semantic action for the production:

In my reply, yesterday, I wrote that I didn't have some concrete suggestions
for solving your problem. But maybe I do:

```
- When using polymorphic semantic values the $$ = $1 action is performed
```

by default for production rules that do not themselves have action
blocks. Those default actions can be suppressed using the --default-actions=no
option. Using this option might significantly reduce the number of copies of
semantic values, especially in cases where these copies are in fact not being
used. 

```
- More importantly, and potentially more effectively, is that $$ values
```

are now _copied_ to the semantic value stack. Those actions require cloning of
the actual data type, which might require relatively expensive
operations. It's likely that instead of copying values _moving_ operations
could be used. Right now I can't tell you whether that's a viable
modification, but it's certainly worth investigating. Once I know more I'll
let you know.

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by yusefmhg** [comment]
I got to the same conclusions yesterday (2 AM now here in Brasil :D). I try disabling the default rules (no significant improvement) and changing the grammar to reduce the quantity of copy assignments in the action rules, which made the generated parser as fast as before.

Once again, thank you very much for the bisonc++ project as well for your reply!

**Comment by fbb-git** [comment]
Dear yusefmhg, you wrote:

> I got to the same conclusions yesterday (2 AM now here in Brasil :D). I try
> disabling the default rules (no significant improvement) and changing the
> grammar to reduce the quantity of copy assignments in the action rules, which
> made the generated parser as fast as before.

Thank for the reply: 2 AM, that's way past children's bedtime :-). I'm in
India right now, and so we're almost at opposite sides of the world... 

Nice to know that your problems has been solved. In the meantime I did a
little experiment using std::move instead of std copy operations implemented
in bisonc++ itself, and that works fine. Need to do some more tests, but when
completed successfully we'll soon have version 5.02.00.

Cheers,

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by fbb-git** [comment]
Hi  yusefmhg,

Continuing our discussion: I've slightly modified the
/usr/share/bisonc++/bisonc++/cc skeleton file, so that the number of
constructed copies of semantic values are significantly reduced. Tests so far
indicate that this does not otherwise affect generated parsers. It's still a
bit early for an official new release (as in addition to the skeleton some of
the documentation files need to be updated), but you might already now want to
give it a try. Simply copying the attached file to
/usr/share/bisonc++/bisonc++.cc is all that's required.

Cheers,

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by yusefmhg** [comment]
Hi,
I saw the commit yesterday, but only now I had some time to test it. I don't know how much it will be useful, but these were the tests I did and the results found:
To test it I used 2 versions of the same grammar file, the first one on a "traditional" approach, using mostly $-notation assignments on the action rules, and the second one trying to minimize the quantity of assignments. The intermediate representation object resultant of the parsing operation was the same in both versions of the grammar, so for practical purposes they were equivalent. To compare performance I generated parsers, with the same grammar files, using versions 4.13, 5.00, 5.01 and the new code (which I dubbed 5.move :D ), with only small changes to the action rules to adjust for versions input differences. Other than these, there weren't differences in the parser generation process (i.e. I used the same scanner, generated with flexc++, the same included files for the polymorphic types, and the same main function, all compiled with g++ 5.3.1, -std=c++14). Then I made the resulting programs parse a small input ( a 7 thousand lines file, almost 200 KBytes).
The following table shows the time taken by the program generated by each version to parse the input:

```
             Version       4.13    5.00    5.01    5.move
Traditional Approach      0.169s  6.602s  6.236s  1.420s
Minimized Assignments     0.160s  0.153s  0.150s  0.116s
```

The tests were repeated a few times for each version and showed no more than a slight variation in the time taken.

Using the traditional approach, 5.XX versions were slower, with good improvement for the new code. Minimizing assignment operations, the performance improves drastically, with small improvements version 5 onwards. We can clearly see how the last changes improved the software for the traditional approach, however I don't think the difference in performance between approaches is consequence only of the code generated by bisonc++ (probably my own code could be improved using a little move-semantics here and some rvalues references there, so I will check it int the next days :D).
Of course, this test weren't as extensive enough, and considers only one specific grammar (which is made to partially load .obj files), so no definitive conclusion can be drawn from them, but I hope the information provided can be useful in someway.

Saudações,

**Comment by fbb-git** [comment]
Dear yusefmhg, you wrote:

> To test it I used 2 versions of the same grammar file, the first one on a
> "traditional" approach, using mostly $-notation assignments on the action
> rules, and the second one trying to minimize the quantity of assignments. 

That's a very interesting and useful test you performed: thanks!
Considering the restults:

> ```
>          Version       4.13    5.00    5.01    5.move
> ```
> 
> Traditional Approach      0.169s  6.602s  6.236s  1.420s
> Minimized Assignments     0.160s  0.153s  0.150s  0.116s

It might be useful for me if you could clarify the difference between the
traditional approach and minimized assignments a bit. In essence, the
difference between release 4 and 5 that relates to the current test is that
release 4 used shared_ptrs and 5 doesn't anymore. That might imply some
overhead in assigning values to the parser's semantic value stack. Shared_ptrs
by themselves require some processing overhead, and and alternative could be
using unique_ptrs, in which case very little needs to be assigned, except for
one or two pointers. That option would require some additional research, and
for that it would be useful to know, preferably in a prototypical example,
what it is you do when implementing 'minimized assignments'.

Another option could be to send me your parser, program and test-data
(preferably directly to my f.b.brokken@rug.nl address), so I can perform the
tests myself, and use them too for testing the effects of using unique_ptrs.

But in any case, your contribution is highly valued! Thanks!

Cheers,

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by yusefmhg** [comment]
Hello,

Sorry for the delay to reply (really busy week at work, so everything else was on hold...). To clarify the difference between (what I called) traditional approach and the "minimized quantity of assignments" approach: The final product of my parser is an object representing a vertex mesh. With the former approach the semantic value of non-terminals were assigned in its action and added to the mesh in the actions of latter reductions. In the latter approach I skip the assignment step, adding the value to the mesh as soon as possible (i.e. int the action that generates the value). I'll send you an e-mail with both approaches, to let it more clear.

Once again, thank you very much.

Saudações,

**Comment by fbb-git** [comment]
Dear yusefmhg, you wrote:

> Hello,
> 
> Sorry for the delay to reply (really busy week at work, so everything else
> was on hold...). To clarify the difference between (what I called) traditional
> ...
> action that generates the value). I'll send you an e-mail with both
> approaches, to let it more clear.

Thanks for your reply. In the meantime bisonc++ 5.02.01 was prepared and
finished: inside the parser itself no semantic values are copied anymore, and
all semantic value copies that remain are implemented in the grammar
production rules' action blocks. I think that should solve the problems you
encountered. I intend to use your example (thanks for sending it to me) to 
check all this, but maybe you beat me in speed and find the time to perform
the checks yourself before I found the time to do so. If so, plese let me know
your findings.

> Once again, thank you very much.

And the same in return,

Cheers,

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```
