### ISSUE TITLE
Build LOG is broken

### ISSUE THREAD

**Issue by gendx** [fbb-git/bisoncpp#8]
I installed the latest version of `bisonc++`:

```
git clone https://github.com/fbb-git/bisoncpp/
cd bisoncpp/bisonc++
./build program strip
sudo ./build install LOG:.bisoncpp bs
```

but the log file `.bisoncpp` only contains:

```
dir /
```

which is not very useful...

Also, the command `build install` prints to stdout the following:

```
mkdir -p tmp/install/
  installing the executable `tmp/install/b//usr/bin/bisonc++'
mkdir -p tmp/install/b//usr/bin
cp tmp/bin/binary tmp/install/b//usr/bin/bisonc++
...
```

which seems weird because the string `tmp/install/b/` is prepended to all the paths, but in reality the files are installed to e.g. `/usr/bin/bisonc++`. This weird behavior also applies to `flexc++` and `bobcat` although their LOG files seem OK.

**Comment by fbb-git** [comment]
Dear gendx, you wrote:

> I installed the latest version of `bisonc++`:
> 
> ```
> git clone https://github.com/fbb-git/bisoncpp/
> cd bisoncpp/bisonc++
> ./build program strip
> sudo ./build install LOG:.bisoncpp bs
> ```
> 
> but the log file `.bisoncpp` only contains:
> 
> ```
> dir /
> ```

Hm, strange. When I do 

./build install LOG:.bisoncpp bs /tmp/bis

I get a file .bisoncpp that starts with

a270c76411847d5647ec3bc32e96369f  /tmp/bis/b/usr/bin/bisonc++
a270c76411847d5647ec3bc32e96369f  /tmp/bis/usr/bin/bisonc++
6bf570a4ff3b614efc939cbeb7b1155c  /tmp/bis/d/usr/share/doc/bisonc++/changelog.gz
beec5f25fac2bdaa1db3fe7fed945619  /tmp/bis/a/usr/share/doc/bisonc++-doc/examples/regression/notused/doc
72e511970d1e590f82570ade19d854fc  /tmp/bis/a/usr/share/doc/bisonc++-doc/examples/regression/notused/parser/grammar
aab53c91f334b5fb75497341db3e5888  /tmp/bis/a/usr/share/doc/bisonc++-doc/examples/regression/fun/doc
54fcf57a178069319abdc4d399b49c9f  /tmp/bis/a/usr/share/doc/bisonc++-doc/examples/regression/fun/demo.cc

and ends with 

dir /tmp/bis/a/usr/share/doc/bisonc++-doc/examples/calculator/scanner
dir /tmp/bis/a/usr/share/doc/bisonc++-doc/examples/bison++Example.NEW
dir /tmp/bis/a/usr/share/doc/bisonc++-doc/bison-docs
dir /tmp/bis/m
dir /tmp/bis/m/usr
dir /tmp/bis/m/usr/share
dir /tmp/bis/m/usr/share/man
dir /tmp/bis/m/usr/share/man/man7
dir /tmp/bis/m/usr/share/man/man1
dir /tmp/bis/m/usr/share/man/man3
dir /tmp/bis/s
dir /tmp/bis/s/usr
dir /tmp/bis/s/usr/share
dir /tmp/bis/s/usr/share/bisonc++

Therefore, so far, I can't reproduce your observation.

> Also, the command `build install` prints to stdout the following:
> 
> ```
> mkdir -p tmp/install/
>   installing the executable `tmp/install/b//usr/bin/bisonc++'
> mkdir -p tmp/install/b//usr/bin
> cp tmp/bin/binary tmp/install/b//usr/bin/bisonc++
> ...
> ```

Same here. If I do 'build install' the reply merely is

  Installation completed

which is OK, as no installation was requested: build install needs a selection
character or characters (which you can verify by just starting ./build).

Just to be sure: the build script expects icmake >= V8.01.00.

So for the time being I can't confirm your observations or offer fixes. Sorry
about that.

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by fbb-git** [comment]
Dear gendx, you wrote:

> I installed the latest version of `bisonc++`:
> 
> ```
> git clone https://github.com/fbb-git/bisoncpp/
> cd bisoncpp/bisonc++
> ./build program strip
> sudo ./build install LOG:.bisoncpp bs
> ```

Well, maybe there _is_ something not completely the way it should be. So,
please stand by for a little while. I'll get back to you asap.

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by fbb-git** [comment]
Dear gendx, you wrote:

> I installed the latest version of `bisonc++`:
> 
> ```
> git clone https://github.com/fbb-git/bisoncpp/
> cd bisoncpp/bisonc++
> ./build program strip
> sudo ./build install LOG:.bisoncpp bs
> ```
> 
> but the log file `.bisoncpp` only contains:
> 
> ```
> dir /
> ```

Hi Gendx,

I think I fixed the problem: so far 'build install LOG:etc.etc' appear to work
as intended. A pushed 5.02.01-pre as a preliminary release: I'm a bit short on
time the coming days, so I can't do extensive tests, but install with sections
b and s and subsequent uninstall requests successfully completed.

Thanks for the bug-report!

Cheers,

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```
