### ISSUE TITLE
Error building  bisoncpp  with clang

### ISSUE THREAD

**Issue by slacka** [fbb-git/bisoncpp#9]
Building  bisoncpp  with clang results in:

`./parser/parserbase.h:317:24: error: reference to non-static member function must be called; did you mean to call it with no arguments?`

The full log can be found here:
http://clang.debian.net/logs/2016-08-30/bisonc++_5.02.00-1_unstable_clang.log

**Comment by fbb-git** [comment]
Dear slacka, you wrote:

> Building  bisoncpp  with clang results in:
> 
> `./parser/parserbase.h:317:24: error: reference to non-static member function must be called; did you mean to call it with no arguments?`
> 
> The full log can be found here:
> http://clang.debian.net/logs/2016-08-30/bisonc++_5.02.00-1_unstable_clang.log

Thanks for reporting this problem.

Maybe you can clarify a few points:

```
- why use clang? 
- in parser/parserbase.h line 317 I see a declaration of a member debug(),
    but in the error log the compiler complains about calling reset with a
    Semantic object. At this point I don't see the relationship between
    the reported line and file and the error message.
```

Please advise,

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by fbb-git** [comment]
Since I received no replies to the above question, I'm closing this issue.

**Comment by slacka** [comment]
sorry for the delayed response. I'll try again with a more recent build of bisoncpp and report back if clang still complains.

**Comment by fbb-git** [comment]
Dear slacka, you wrote:

> sorry for the delayed response. I'll try again with a more recent build of
> bisoncpp and report back if clang still complains.

OK, thanks for your reply. I'll certainly investigate the problem if it
persists, but since the error message and the actual sources didn't match, I
was groping in the dark, and saw no other option than to close the issue.

Cheers,

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by TimAllman** [comment]
I am currently finding the same problem which goes away when I use gcc.

_/home/tim/devel/lexyacc/Parserbase.h:294: error: reference to non-static member function must be called; did you mean to call it with no arguments?
    reset(new Semantic<tag>(std::forward<Args>(args) ...));_

The tools are:
_clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu_
and
_bisonc++ V6.01.00_

**Comment by fbb-git** [comment]
Dear Tim Allman, you wrote:

> I am currently finding the same problem which goes away when I use gcc.

Note that github is no longer bisconc++'s 'home base'. Use gitlab.

> https://github.com/fbb-git/bisoncpp/issues/9#issuecomment-558807154

-- 
    Frank B. Brokken
    (+31) 6 5353 2509
    PGP Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
